# frozen_string_literal: true

BUILD_DIR = 'build'

task :build do
  sh 'cmake', '-G', 'Ninja', '-B', BUILD_DIR, '-DCMAKE_BUILD_TYPE=Debug'
  sh 'cmake', '--build', BUILD_DIR, '-v'
end

task run: :build do
  sh File.join(BUILD_DIR, 'lit'), 'help'
end

task :format do
  sh 'rubocop', '--fix'
  sh 'clang-format', '-i', *Dir.glob('**/*.{c,h}xx')
end

task :lint do
  sh 'rubocop'
  sh 'clang-format', *Dir.glob('**/*.{c,h}xx')
end

task :clean do
  rm_rf BUILD_DIR
end

task default: :build
