name: CI

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run rubocop
        uses: reviewdog/action-rubocop@v1

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.10

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release, Debug]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          brew install gcc@10

          cmake -S lit -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build -v
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Test
        run: |
          export PATH="${PWD}/lit/build:${PATH}"

          bash -x lit/test/integration.sh
